# This file is generated when builtins.py is compiled.
InternalInvokers = [
  (0, "Close"),
  (0, "Flush"),
  (0, "Wait"),
  (0, "Warm"),
  (0, "__init__"),
  (0, "clear"),
  (0, "close"),
  (0, "copy"),
  (0, "flush"),
  (0, "isalnum"),
  (0, "isalpha"),
  (0, "isdigit"),
  (0, "islower"),
  (0, "isspace"),
  (0, "isupper"),
  (0, "items"),
  (0, "iter"),
  (0, "iteritems"),
  (0, "iterkeys"),
  (0, "itervalues"),
  (0, "keys"),
  (0, "lower"),
  (0, "read"),
  (0, "reverse"),
  (0, "title"),
  (0, "upper"),
  (0, "values"),
  (1, "Raise"),
  (1, "Recv"),
  (1, "Send"),
  (1, "Start"),
  (1, "Write"),
  (1, "__getattr__"),
  (1, "append"),
  (1, "count"),
  (1, "endswith"),
  (1, "extend"),
  (1, "find"),
  (1, "has_key"),
  (1, "index"),
  (1, "join"),
  (1, "lstrip"),
  (1, "pop"),
  (1, "remove"),
  (1, "rfind"),
  (1, "rindex"),
  (1, "rstrip"),
  (1, "startswith"),
  (1, "strip"),
  (1, "update"),
  (1, "write"),
  (2, "__init__"),
  (2, "__setattr__"),
  (2, "get"),
  (2, "insert"),
  (2, "setdefault"),
  (2, "split"),
  (3, "replace"),
  (3, "sort"),
  ]
# FooBarBaz
InternalGetters = [
  "Close",
  "Flush",
  "Raise",
  "Recv",
  "Send",
  "Start",
  "Wait",
  "Warm",
  "Write",
  "__getattr__",
  "__init__",
  "__setattr__",
  "append",
  "clear",
  "close",
  "copy",
  "count",
  "endswith",
  "extend",
  "find",
  "flush",
  "get",
  "has_key",
  "index",
  "insert",
  "isalnum",
  "isalpha",
  "isdigit",
  "islower",
  "isspace",
  "isupper",
  "items",
  "iter",
  "iteritems",
  "iterkeys",
  "itervalues",
  "join",
  "keys",
  "lower",
  "lstrip",
  "pop",
  "read",
  "remove",
  "replace",
  "reverse",
  "rfind",
  "rindex",
  "rstrip",
  "setdefault",
  "sort",
  "split",
  "startswith",
  "strip",
  "title",
  "update",
  "upper",
  "values",
  "write",
  ]
InternalSetters = [
  ]
